name: Python type check

on:
  push:
    branches: [ master ]
    tags: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  mypy:
    runs-on: ubuntu-20.04
    env:
      branch: Jul2021
    container: monetdb/dev-builds:{{ env.branch }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install MonetDBe in developer mode
        run: MONETDB_BRANCH={{ env.branch }} python3 -m pip install -e .[test]
      -
        name: Run mypy static code checks
        run: mypy monetdbe tests